import path from "node:path";
import { monitorEventLoopDelay } from "node:perf_hooks";
import { ClaudeAgent } from "../src/claude-agent.ts";
import { render } from "../src/claude-thread-events.ts";
import { pageOf, readClaudeHistory } from "../src/thread-history.ts";
const claude = "/workspace/packages/server/.bench/big/claude";
const h = monitorEventLoopDelay({ resolution: 1 }); h.enable();
const tick = setInterval(() => {}, 1);
await new Promise(r => setTimeout(r, 50));
if (process.argv[2] === "old") pageOf(render(ClaudeAgent.stored(claude)!, null, null, path.join(claude, "claude")), {});
else await readClaudeHistory(path.join(claude, "claude.sqlite"), path.join(claude, "claude"), null, null, {});
await new Promise(r => setTimeout(r, 20));
clearInterval(tick); h.disable();
console.log(process.argv[2], "max event-loop delay", (h.max / 1e6).toFixed(0), "ms");
