//! Runner protocol 4 (`cubeyard/runner/4`): the types of proto/runner.proto
//! (prost messages with proto3-JSON serde, generated by build.rs) and the
//! stream framing both ends use. berth serves it; cubed's TypeScript client
//! is generated from the same file (packages/server/src/runner-session.ts).
pub mod proto {
    #![allow(clippy::all, clippy::pedantic, missing_docs)]
    include!(concat!(env!("OUT_DIR"), "/cube.runner.v4.rs"));
    include!(concat!(env!("OUT_DIR"), "/cube.runner.v4.serde.rs"));
}

use chrono::{DateTime, SecondsFormat, Utc};
use serde::{Deserialize, Deserializer, Serialize, Serializer, de::Error as _};

/// `google.protobuf.Timestamp` in its proto3 JSON form (RFC 3339 in UTC
/// with `Z`, 0, 3, 6 or 9 fractional digits).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Timestamp {
    #[prost(int64, tag = "1")]
    pub seconds: i64,
    #[prost(int32, tag = "2")]
    pub nanos: i32,
}

impl Timestamp {
    pub fn now() -> Self {
        Self::from(std::time::SystemTime::now())
    }
}

impl From<std::time::SystemTime> for Timestamp {
    fn from(time: std::time::SystemTime) -> Self {
        let since = time
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default();
        Self {
            seconds: since.as_secs() as i64,
            nanos: since.subsec_nanos() as i32,
        }
    }
}

impl Serialize for Timestamp {
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        let time = DateTime::<Utc>::from_timestamp(self.seconds, self.nanos as u32)
            .ok_or_else(|| serde::ser::Error::custom("timestamp out of range"))?;
        serializer.serialize_str(&time.to_rfc3339_opts(SecondsFormat::AutoSi, true))
    }
}

impl<'de> Deserialize<'de> for Timestamp {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let text = String::deserialize(deserializer)?;
        let time = DateTime::parse_from_rfc3339(&text).map_err(D::Error::custom)?;
        Ok(Self {
            seconds: time.timestamp(),
            nanos: time.timestamp_subsec_nanos() as i32,
        })
    }
}

use anyhow::{Result, ensure};
use tokio::io::{AsyncRead, AsyncReadExt, AsyncWrite, AsyncWriteExt};

pub const ALPN: &[u8] = b"cubeyard/runner/4";
pub const PROTOCOL: u32 = 4;
/// A header frame (`Open`, an answer, a watch event).
pub const MAX_FRAME_BYTES: usize = 1024 * 1024;

pub fn refuse(code: proto::Code, reason: &str, message: &str) -> proto::Error {
    proto::Error {
        code: code as i32,
        reason: reason.into(),
        message: message.chars().take(1024).collect(),
        completion_unknown: false,
    }
}

/// u32 big-endian length, then that many bytes of proto3 JSON.
pub async fn write_frame<T: Serialize>(
    send: &mut (impl AsyncWrite + Unpin),
    value: &T,
) -> Result<()> {
    let payload = serde_json::to_vec(value)?;
    ensure!(payload.len() <= MAX_FRAME_BYTES, "frame exceeds limit");
    let mut bytes = Vec::with_capacity(4 + payload.len());
    bytes.extend_from_slice(&(payload.len() as u32).to_be_bytes());
    bytes.extend_from_slice(&payload);
    send.write_all(&bytes).await?;
    Ok(())
}

pub async fn read_frame<T: serde::de::DeserializeOwned>(
    recv: &mut (impl AsyncRead + Unpin),
) -> Result<T> {
    let size = recv.read_u32().await? as usize;
    ensure!(size > 0 && size <= MAX_FRAME_BYTES, "invalid frame length");
    let mut payload = vec![0; size];
    recv.read_exact(&mut payload).await?;
    Ok(serde_json::from_slice(&payload)?)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn a_frame_reads_back_as_written() {
        let open = proto::Open {
            kind: Some(proto::open::Kind::Guest(proto::GuestHeader {
                r#ref: Some(proto::Ref {
                    owner: "thread".into(),
                    id: "0123456789abcdef".into(),
                }),
                fence: Some(proto::Fence { epoch: 7 }),
                op: "hello".into(),
            })),
        };
        let mut bytes = Vec::new();
        write_frame(&mut bytes, &open).await.unwrap();
        assert_eq!(&bytes[4..], br#"{"guest":{"ref":{"owner":"thread","id":"0123456789abcdef"},"fence":{"epoch":"7"},"op":"hello"}}"#);
        let read: proto::Open = read_frame(&mut &bytes[..]).await.unwrap();
        assert_eq!(read, open);
        assert!(
            read_frame::<proto::Open>(&mut &[0u8, 0, 0, 0][..])
                .await
                .is_err(),
            "an empty frame is refused"
        );
    }
}
