//! Runner protocol 4 (`cubeyard/runner/4`): the types of proto/runner.proto
//! (prost messages with proto3-JSON serde, generated by build.rs) and the
//! stream framing both ends use. berth serves it; cubed's TypeScript client
//! is generated from the same file (packages/server/src/runner-session.ts).
pub mod proto {
    #![allow(clippy::all, clippy::pedantic, missing_docs)]
    include!(concat!(env!("OUT_DIR"), "/cube.runner.v4.rs"));
    include!(concat!(env!("OUT_DIR"), "/cube.runner.v4.serde.rs"));
}

use chrono::{DateTime, SecondsFormat, Utc};
use serde::{Deserialize, Deserializer, Serialize, Serializer, de::Error as _};

/// `google.protobuf.Timestamp` in its proto3 JSON form (RFC 3339 in UTC
/// with `Z`, 0, 3, 6 or 9 fractional digits).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Timestamp {
    #[prost(int64, tag = "1")]
    pub seconds: i64,
    #[prost(int32, tag = "2")]
    pub nanos: i32,
}

impl Timestamp {
    pub fn now() -> Self {
        Self::from(std::time::SystemTime::now())
    }
}

impl From<std::time::SystemTime> for Timestamp {
    fn from(time: std::time::SystemTime) -> Self {
        let since = time
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default();
        Self {
            seconds: since.as_secs() as i64,
            nanos: since.subsec_nanos() as i32,
        }
    }
}

impl Serialize for Timestamp {
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        let time = DateTime::<Utc>::from_timestamp(self.seconds, self.nanos as u32)
            .ok_or_else(|| serde::ser::Error::custom("timestamp out of range"))?;
        serializer.serialize_str(&time.to_rfc3339_opts(SecondsFormat::AutoSi, true))
    }
}

impl<'de> Deserialize<'de> for Timestamp {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let text = String::deserialize(deserializer)?;
        let time = DateTime::parse_from_rfc3339(&text).map_err(D::Error::custom)?;
        Ok(Self {
            seconds: time.timestamp(),
            nanos: time.timestamp_subsec_nanos() as i32,
        })
    }
}

use anyhow::{Result, bail, ensure};
use tokio::io::{AsyncRead, AsyncReadExt, AsyncWrite, AsyncWriteExt};

pub const ALPN: &[u8] = b"cubeyard/runner/4";
pub const PROTOCOL: u32 = 4;
/// A header frame (`Open`, an answer, a watch event).
pub const MAX_FRAME_BYTES: usize = 1024 * 1024;

pub fn refuse(code: proto::Code, reason: &str, message: &str) -> proto::Error {
    proto::Error {
        code: code as i32,
        reason: reason.into(),
        message: message.chars().take(1024).collect(),
        completion_unknown: false,
    }
}

/// u32 big-endian length, then that many bytes of proto3 JSON.
pub async fn write_frame<T: Serialize>(
    send: &mut (impl AsyncWrite + Unpin),
    value: &T,
) -> Result<()> {
    let payload = serde_json::to_vec(value)?;
    ensure!(payload.len() <= MAX_FRAME_BYTES, "frame exceeds limit");
    let mut bytes = Vec::with_capacity(4 + payload.len());
    bytes.extend_from_slice(&(payload.len() as u32).to_be_bytes());
    bytes.extend_from_slice(&payload);
    send.write_all(&bytes).await?;
    Ok(())
}

pub async fn read_frame<T: serde::de::DeserializeOwned>(
    recv: &mut (impl AsyncRead + Unpin),
) -> Result<T> {
    Ok(serde_json::from_slice(&read_payload(recv).await?)?)
}

async fn read_payload(recv: &mut (impl AsyncRead + Unpin)) -> Result<Vec<u8>> {
    let size = recv.read_u32().await? as usize;
    ensure!(size > 0 && size <= MAX_FRAME_BYTES, "invalid frame length");
    let mut payload = vec![0; size];
    recv.read_exact(&mut payload).await?;
    Ok(payload)
}

/// A guest's `hello` or `status` at most: the runner passes it on in a
/// watch event.
pub const MAX_GUEST_INFO_BYTES: usize = 64 * 1024;

/// One `DaemonFrame` from the guest channel, held to the channel's rules
/// (runner.proto's header): `hello` and `status` on channel 0 and at most
/// MAX_GUEST_INFO_BYTES, everything else on a channel above 0, and a
/// request or answer that says what it is. An error ends the connection.
pub async fn read_daemon_frame(recv: &mut (impl AsyncRead + Unpin)) -> Result<proto::DaemonFrame> {
    use proto::daemon_frame::T;
    let payload = read_payload(recv).await?;
    let frame: proto::DaemonFrame = serde_json::from_slice(&payload)?;
    match &frame.t {
        None => bail!("a frame of no known kind"),
        Some(T::Hello(_) | T::Status(_)) => {
            ensure!(frame.ch == 0, "hello and status belong on channel 0");
            ensure!(
                payload.len() <= MAX_GUEST_INFO_BYTES,
                "the guest's status is too large"
            );
        }
        Some(T::Req(request)) => {
            ensure!(frame.ch > 0, "an operation needs a channel above 0");
            ensure!(request.op.is_some(), "a request of no known kind");
        }
        Some(T::Ans(answer)) => {
            ensure!(frame.ch > 0, "an operation needs a channel above 0");
            ensure!(answer.result.is_some(), "an answer of no known kind");
        }
        Some(T::Abort(_)) => ensure!(frame.ch > 0, "an operation needs a channel above 0"),
    }
    Ok(frame)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn a_frame_reads_back_as_written() {
        let open = proto::Open {
            kind: Some(proto::open::Kind::Guest(proto::GuestHeader {
                r#ref: Some(proto::Ref {
                    owner: "thread".into(),
                    id: "0123456789abcdef".into(),
                }),
                fence: Some(proto::Fence { epoch: 7 }),
                op: "hello".into(),
            })),
        };
        let mut bytes = Vec::new();
        write_frame(&mut bytes, &open).await.unwrap();
        assert_eq!(&bytes[4..], br#"{"guest":{"ref":{"owner":"thread","id":"0123456789abcdef"},"fence":{"epoch":"7"},"op":"hello"}}"#);
        let read: proto::Open = read_frame(&mut &bytes[..]).await.unwrap();
        assert_eq!(read, open);
        assert!(
            read_frame::<proto::Open>(&mut &[0u8, 0, 0, 0][..])
                .await
                .is_err(),
            "an empty frame is refused"
        );
    }

    fn framed(json: &[u8]) -> Vec<u8> {
        let mut bytes = (json.len() as u32).to_be_bytes().to_vec();
        bytes.extend_from_slice(json);
        bytes
    }

    #[tokio::test]
    async fn the_guest_channel_frames_as_the_streams_do() {
        use proto::{daemon_frame::T, daemon_request::Op};
        let frame = proto::DaemonFrame {
            ch: 3,
            t: Some(T::Req(proto::DaemonRequest {
                op: Some(Op::Guest(proto::GuestRequest {
                    op: "hello".into(),
                    data: b"{}\n".to_vec(),
                })),
            })),
        };
        let mut bytes = Vec::new();
        write_frame(&mut bytes, &frame).await.unwrap();
        let json = br#"{"ch":3,"req":{"guest":{"op":"hello","data":"e30K"}}}"#;
        assert_eq!(bytes, framed(json));
        assert_eq!(&bytes[..4], &[0, 0, 0, 53]);
        assert_eq!(read_daemon_frame(&mut &bytes[..]).await.unwrap(), frame);

        let setup = br#"{"ch":1,"req":{"machineSetup":{"ref":{"owner":"t1","id":"0123456789abcdef"},"documents":{"hostname":"Y3ViZS0wMTIzNDU2Nwo=","env":"R0hfVE9LRU49Y3ViZV9waF9naXRodWJfeAo="},"entropy":"AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8=","layers":[{"partition":2,"templateId":"tpl"},{"partition":1,"diffId":"sha256:ab"}],"protocol":4}}}"#;
        let read = read_daemon_frame(&mut &framed(setup)[..]).await.unwrap();
        let Some(T::Req(proto::DaemonRequest {
            op: Some(Op::MachineSetup(setup)),
        })) = read.t
        else {
            panic!("expected a machine setup, got {read:?}");
        };
        assert_eq!(setup.documents["hostname"], b"cube-01234567\n");
        assert_eq!(setup.documents["env"], b"GH_TOKEN=cube_ph_github_x\n");
        assert_eq!(setup.entropy, (0u8..32).collect::<Vec<_>>());
        let sources: Vec<_> = setup
            .layers
            .iter()
            .map(|layer| (layer.partition, layer.source.clone()))
            .collect();
        assert_eq!(
            sources,
            [
                (2, Some(proto::layer::Source::TemplateId("tpl".into()))),
                (1, Some(proto::layer::Source::DiffId("sha256:ab".into()))),
            ]
        );
    }

    #[tokio::test]
    async fn the_guest_channel_refuses_what_breaks_its_rules() {
        let big_hello = format!(
            r#"{{"ch":0,"hello":{{"reason":"{}"}}}}"#,
            "x".repeat(MAX_GUEST_INFO_BYTES)
        );
        let cases: Vec<(Vec<u8>, &str)> = vec![
            (vec![0, 0, 0, 0], "invalid frame length"),
            (
                (MAX_FRAME_BYTES as u32 + 1).to_be_bytes().to_vec(),
                "invalid frame length",
            ),
            (vec![0, 0, 0, 10, b'{', b'}'], "early eof"),
            (framed(b"not json"), "expected ident"),
            (
                framed(br#"{"ch":1,"shout":{}}"#),
                "a frame of no known kind",
            ),
            (
                framed(br#"{"ch":1,"hello":{"ready":true}}"#),
                "hello and status belong on channel 0",
            ),
            (
                framed(br#"{"ch":2,"status":{}}"#),
                "hello and status belong on channel 0",
            ),
            (
                framed(br#"{"ch":0,"req":{"snapshotDone":{}}}"#),
                "an operation needs a channel above 0",
            ),
            (
                framed(br#"{"ch":0,"abort":{}}"#),
                "an operation needs a channel above 0",
            ),
            (
                framed(br#"{"ch":4,"req":{}}"#),
                "a request of no known kind",
            ),
            (
                framed(br#"{"ch":4,"ans":{"later":{}}}"#),
                "an answer of no known kind",
            ),
            (
                framed(big_hello.as_bytes()),
                "the guest's status is too large",
            ),
        ];
        for (bytes, why) in cases {
            let error = read_daemon_frame(&mut &bytes[..]).await.unwrap_err();
            assert!(error.to_string().contains(why), "{why}: got {error}");
        }
        let hello = framed(br#"{"ch":0,"hello":{"ready":false,"reason":"gh is missing"}}"#);
        let read = read_daemon_frame(&mut &hello[..]).await.unwrap();
        let Some(proto::daemon_frame::T::Hello(info)) = read.t else {
            panic!("{read:?}")
        };
        assert_eq!((info.ready, info.reason.as_str()), (false, "gh is missing"));
    }

    #[tokio::test]
    async fn a_largest_guest_write_and_read_fit_one_frame() {
        use proto::{daemon_answer::Result as Answer, daemon_frame::T, daemon_request::Op};
        // cube-guest's limits: 512 KiB reads and writes, 4 KiB paths.
        let header = format!(
            r#"{{"key":"{}","path":"{}","epoch":1}}"#,
            "k".repeat(128),
            "p".repeat(4096)
        );
        let mut data = format!("{header}\n").into_bytes();
        data.extend(std::iter::repeat_n(0xff, 512 * 1024));
        let request = proto::DaemonFrame {
            ch: u32::MAX,
            t: Some(T::Req(proto::DaemonRequest {
                op: Some(Op::Guest(proto::GuestRequest {
                    op: "write".into(),
                    data: data.clone(),
                })),
            })),
        };
        let answer = proto::DaemonFrame {
            ch: u32::MAX,
            t: Some(T::Ans(proto::DaemonAnswer {
                result: Some(Answer::Guest(data)),
            })),
        };
        for frame in [request, answer] {
            let mut bytes = Vec::new();
            write_frame(&mut bytes, &frame).await.unwrap();
            assert!(bytes.len() < 800 * 1024, "{} bytes", bytes.len());
            assert_eq!(read_daemon_frame(&mut &bytes[..]).await.unwrap(), frame);
        }
    }
}
